### PR TITLE
Upgrade to ubuntu 20.04 and nginx stable 1.18.0

### PR DESCRIPTION
**Pull request by thelittlefireman**

### CODE REVIEW

**Comment by coderpatros** [comment]
@thelittlefireman I've got some conflicting priorities at the moment. It's probably simple enough. But I don't have the time right now to figure out why the build has failed. If you want to, it would be most appreciated. Otherwise I'll probably get to this in a week or two.

**Comment by thelittlefireman** [comment]
@coderpatros Seems to be ok now :) Could you run a build and let me now please ?

**Comment by thelittlefireman** [comment]
@coderpatros I just add brotli module support too :)

ref [https://www.majlovesreg.one/adding-brotli-to-a-built-nginx-instance](https://www.majlovesreg.one/adding-brotli-to-a-built-nginx-instance)

**Comment by coderpatros** [comment]
Thanks @thelittlefireman LGTM

**Pull request merged**
